<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bootstrap" nsURI="urn:org.nasdanika.vinci.bootstrap" nsPrefix="org.nasdanika.vinci.bootstrap">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Model of Bootstrap elements."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EDataType" name="IBootstrapElement" instanceClassName="org.nasdanika.html.bootstrap.BootstrapElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BootstrapElement" eSuperTypes="../../org.nasdanika.vinci.html/model/html.ecore#//HtmlElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//Row"
        containment="true"/>
    <eGenericSuperTypes eClassifier="#//BootstrapElement"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.ncore/model/ncore.ecore#//CommandFactory">
      <eTypeArguments eClassifier="#//IBootstrapElement"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Row" eSuperTypes="#//BootstrapElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//Column" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="#//BootstrapElement ../../org.nasdanika.vinci.html/model/html.ecore#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Card">
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" eType="#//Div"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1" eType="#//Div"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="footer" eType="#//Div"
        containment="true"/>
    <eGenericSuperTypes eClassifier="#//BootstrapElement"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.ncore/model/ncore.ecore#//CommandFactory">
      <eTypeArguments eClassifier="#//IBootstrapElement"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag" eSuperTypes="../../org.nasdanika.vinci.html/model/html.ecore#//Tag #//BootstrapElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="HTML tag with bootstrap styling"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Div" eSuperTypes="#//Tag">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="HTML DIV with bootstrap styling"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alert" eSuperTypes="#//Div">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Color" instanceClassName="org.nasdanika.html.bootstrap.Color"/>
  <eClassifiers xsi:type="ecore:EClass" name="Badge" eSuperTypes="#//Div">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//Div">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="TODO - size - enum? Block, active, disabled."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ButtonGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="ButtonToolbar"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dropdown"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="Breadcrumbs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Form"/>
  <eClassifiers xsi:type="ecore:EClass" name="ListGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="Navs"/>
  <eClassifiers xsi:type="ecore:EClass" name="Navbar"/>
  <eClassifiers xsi:type="ecore:EClass" name="Table"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableColumn"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tooltip"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="FormGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="Collapse"/>
  <eClassifiers xsi:type="ecore:EClass" name="Modal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Accordion"/>
</ecore:EPackage>
