<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="html" nsURI="urn:org.nasdanika.vinci.html" nsPrefix="org.nasdanika.vinci.html">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="HTML model"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EDataType" name="ITag" instanceClassName="org.nasdanika.html.Tag"/>
  <eClassifiers xsi:type="ecore:EDataType" name="TagName" instanceClassName="org.nasdanika.html.TagName"/>
  <eClassifiers xsi:type="ecore:EClass" name="HtmlElement" abstract="true" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container of content such as text and HTML markup."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="ecore:EClass ../../org.nasdanika.ncore/model/ncore.ecore#//CommandFactory">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//TagName"/>
    <eGenericSuperTypes eClassifier="#//HtmlElement"/>
    <eGenericSuperTypes eClassifier="#//Container"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../org.nasdanika.ncore/model/ncore.ecore#//CommandFactory">
      <eTypeArguments eClassifier="#//ITag"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
